import GameLogic.Util as Util

GAME_READY = 'GameOn'
GAME_START = 'GameStart'
GAME_PREPSTART = 'GamePrepStart'
PLAYER_JOIN = 'PlayerJoin'
GET_BOARD = 'GetBoard'
GAME_PLAY = 'GamePlay'
GAME_FULL = 'GameFull'
GAME_IN_PROGRESS = 'GameInProgress'
PLAYER_DISCONNECT = 'PlayerDisconnect'
BOARD = 'Board'
PLAYER_CAN_JOIN = 'PlayerCanJoin'
GAME_NOT_ENOUGH_PLAYERS = 'GameNotEnoughPlayers'
GAME_OVER = 'GameOver'
DISPLAY_SCORE = 'DisplayScore'

IPADDRESS = 'localhost'
PORTNUMBER = 50000

MAX_PLAYERS = 4
CLIENT_GAME_TIME_IN_SECONDS = 50
SERVER_GAME_TIME_IN_SECONDS = CLIENT_GAME_TIME_IN_SECONDS + Util.GAME_STARTING_TIME + 1
