GAME_READY = 'GameOn'
GAME_START = 'GameStart'
GAME_PREPSTART = 'GamePrepStart'
PLAYER_JOIN = 'PlayerJoin'
GET_BOARD = 'GetBoard'
GAME_PLAY = 'GamePlay'
GAME_RESET = 'GameReset'
GAME_FULL = 'GameFull'
GAME_IN_PROGRESS = 'GameInProgress'
GAME_OVER = "GameOver"
PLAYER_DISCONNECT = 'PlayerDisconnect'
BOARD = 'Board'
PLAYER_CAN_JOIN = 'PlayerCanJoin'
GAME_ERROR = 'GameError'
GAME_NOT_ENOUGH_PLAYERS = 'GameNotEnoughPlayers'
GAME_OVER = 'GameOver'
DISPLAY_SCORE = 'DisplayScore'
START_SERVER_TIMER = 'StartServerTimer'

TESTING_PURPOSES = 'TestingPurposes'

IPADDRESS = 'localhost'
PORTNUMBER = 50000

CLIENT_GAME_TIME_IN_SECONDS = 30
SERVER_GAME_TIME_IN_SECONDS = CLIENT_GAME_TIME_IN_SECONDS + 1
REMAINING_TIME_MSG = "Remaining Time: "
MAX_PLAYERS = 4
